version: '3'

services:
  skills-finder-app:
    build: .
    hostname: skills_finder_app
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=skills_finder_web.settings
    entrypoint: [ "/bin/sh","-c" ]
    command:
      - |
        python manage.py makemigrations
        python manage.py migrate && python manage.py migrate --run-syncdb
        python initial_setup.py
        python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      skills-finder-db:
        condition: service_healthy

  skills-finder-db:
    image: postgres:12.5
    hostname: skills_finder_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 30s
      retries: 6
    restart: always
